server:
  AppVersion: 1.0.0
  Port: :8080
  Mode: development
  ReadTimeout: 5
  WriteTimeout: 5
  CxtDefaultTimeout: 12 
  Debug: false
  JwtSecretKey: mySecretKey

postgres: 
  PostgresDbname: go_instagram_clone_db
  PostgresUser: postgres
  PostgresPassword: postgres
  PostgresPort: 5432
  PostgresHost: localhost
  PostgresSslMode: disable
  PgDriver: pgx
