version: '3.1'

networks:
  web_api:

services:
  mysql:
    image: mysql:5.7   
    restart: always
    container_name: api_mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=go_instagram_clone_analytics_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql_data:/var/lib/mysql 
    networks:
      - web_api